apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ticket-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"  
spec:
  ingressClassName: nginx
  rules:
    - host: ticketing.dev # Should modify /etc/hosts and add this domain if k8s is locally
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port: 
                  number: 3000